### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by DanielChertykovtsev**
have done excersise on first use of GitHub.
Please Accept my Pull&Request

### CODE REVIEW

**Review by AlexeyAnanchenko — APPROVED** [review]
Everything correctly)

**Review by kanai-chan — APPROVED** [review]

**Comment by kanai-chan** [comment]
it`s good job!

**Comment by sashagorbachev** [comment]
#good job, my dear friend

**Review by nezhdanov2000 — COMMENTED** [review]
гуд

**Pull request merged**
